name: "Publish Docker Image"

on:
  push:
    branches: main

jobs:
  build:
    uses: alves-dev/actions/.github/workflows/build-docker.yml@v1
    with:
      image-name: ghcr.io/alves-dev/video-flow-task